#!/usr/bin/env python

import rospy
from nicla_vision_ros import TFOnImage


if __name__ == '__main__':

    rospy.init_node("TF_on_image")

    rate = rospy.Rate(10)

    tf_on_image_node = TFOnImage()

    while not rospy.is_shutdown():

        try:
            tf_on_image_node.run()

        except Exception as e:
            rospy.logerr(e)
            break

        rate.sleep()